### ISSUE TITLE
API Research

### ISSUE THREAD

**Issue by emmareimer** [djmarcy/palabra#6]
- [x] Will API work? - well documented, well organized data
- [x] What are the fetch parameters?
- [x] Link to API

**Comment by JLewis1995** [comment]
var key = "56e1ec2b89msh75f5a1bd9fbcbb6p150a7bjsnb6e951a5a987"
fetch("https://wordsapiv1.p.rapidapi.com/words/?random=true", {
    "method": "GET",
    "headers": {
        "x-rapidapi-host": "[wordsapiv1.p.rapidapi.com](http://wordsapiv1.p.rapidapi.com/)",
        "x-rapidapi-key": "56e1ec2b89msh75f5a1bd9fbcbb6p150a7bjsnb6e951a5a987"
    }
})
.then(function(resp) { return resp.json() }) // Convert data to json
.then(function(data) {
  console.log(data)
})

**Comment by JLewis1995** [comment]
Max 2,500 api calls per day

**Comment by JLewis1995** [comment]
DEFINITION API FETCH

fetch("https://wordsapiv1.p.rapidapi.com/words/incredible/definitions", {
	"method": "GET",
	"headers": {
		"x-rapidapi-host": "wordsapiv1.p.rapidapi.com",
		"x-rapidapi-key": "56e1ec2b89msh75f5a1bd9fbcbb6p150a7bjsnb6e951a5a987"
	}
})
.then(response => {
	console.log(response);
})
.catch(err => {
	console.error(err);
});
